name: build
on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
        
      - name: setup jdk
        uses: actions/setup-java@v1
        with:
          java-version: 8
          
      - name: build with brachyura
        run: java -jar brachyura-bootstrap-0.jar build
        
      - name: capture build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: build/libs/
